service: stripe-shoppingcart

custom:
  customDomain:
    domainName: stripe.myawstester.com
    #basePath: "v1"
    state: ${self:provider.stage}
    certificateName: myawstester.com
    createRoute53Record: true
provider:
  name: aws
  runtime: nodejs10.x
  deploymentBucket:
    name: deploys.myawstester.sls

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

plugins:
  - serverless-domain-manager